{% set version = "1.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pins
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pins_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pins/pins_{{ version }}.tar.gz
  sha256: a9aa8fdea6dfab6005cb722cea4f5561500d678af3e297453d5be297707a38fe

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-digest
    - r-ellipsis
    - r-fs
    - r-generics
    - r-glue
    - r-httr
    - r-jsonlite
    - r-lifecycle
    - r-magrittr
    - r-purrr
    - r-rappdirs
    - r-rlang >=1.1.0
    - r-tibble
    - r-whisker
    - r-withr >=2.4.3
    - r-yaml
  run:
    - r-base
    - r-cli
    - r-digest
    - r-ellipsis
    - r-fs
    - r-generics
    - r-glue
    - r-httr
    - r-jsonlite
    - r-lifecycle
    - r-magrittr
    - r-purrr
    - r-rappdirs
    - r-rlang >=1.1.0
    - r-tibble
    - r-whisker
    - r-withr >=2.4.3
    - r-yaml

test:
  commands:
    - $R -e "library('pins')"           # [not win]
    - "\"%R%\" -e \"library('pins')\""  # [win]

about:
  home: https://pins.rstudio.com/
  dev_url: https://github.com/rstudio/pins
  license: Apache-2.0
  license_file:
    - LICENSE.md
  license_family: APACHE
  summary: Publish data sets, models, and other R objects, making it easy to share them across projects and with your colleagues. You can pin objects to a variety of "boards", including local folders (to share on a networked drive or with 'DropBox'), 'RStudio' connect, Amazon S3, and more.

extra:
  recipe-maintainers:
    - conda-forge/r
